# $$\       $$$$$$$\  $$\   $$\       $$\   $$\                           $$\ $$\
# $$ |      $$  __$$\ $$ |  $$ |      $$ |  $$ |                          $$ |$$ |
# $$ |      $$ |  $$ |\$$\ $$  |      $$ |  $$ | $$$$$$\  $$$$$$$\   $$$$$$$ |$$ | $$$$$$\   $$$$$$\
# $$ |      $$$$$$$  | \$$$$  /       $$$$$$$$ | \____$$\ $$  __$$\ $$  __$$ |$$ |$$  __$$\ $$  __$$\
# $$ |      $$  ____/  $$  $$<        $$  __$$ | $$$$$$$ |$$ |  $$ |$$ /  $$ |$$ |$$$$$$$$ |$$ |  \__|
# $$ |      $$ |      $$  /\$$\       $$ |  $$ |$$  __$$ |$$ |  $$ |$$ |  $$ |$$ |$$   ____|$$ |
# $$$$$$$$\ $$ |      $$ /  $$ |      $$ |  $$ |\$$$$$$$ |$$ |  $$ |\$$$$$$$ |$$ |\$$$$$$$\ $$ |
# \________|\__|      \__|  \__|      \__|  \__| \_______|\__|  \__| \_______|\__| \_______|\__|

#--------! Handler made With ♥ by redgabri & Skrahs !--------#

config-version: 1

#---------! Alerts !---------#

ALERT_MESSAGE:
DEBUG_MESSAGE:
PRINTER_MODE_MESSAGE:


